spring:
  application:
    name: library-crud

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: library
        hbm2ddl:
          create_namespaces: true
    open-in-view: false

  flyway:
    enabled: false

server:
  port: ${PORT:8080}